apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/nginx/*.log
      fields:
        service: nginx
    output.elasticsearch:
      hosts: ['http://elasticsearch-master.elastic-stack.svc.cluster.local:9200']
      username: elastic
      password: A226gIC011IfWWwf